# Generated by Django 3.2 on 2021-06-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210608_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='thibnail',
            new_name='thumbnail',
        ),
    ]
